inherit_from: .rubocop_todo.yml

Naming/FileName:
  Exclude:
    - 'test/test-helper.rb'

Metrics/ParameterLists:
  Max: 18

Metrics/ModuleLength:
  Max: 800

# Offense count: 22
# Configuration parameters: AllowedVariables.
Lint/UselessAssignment:
  Exclude:
    - 'lib/serrano/filters.rb'

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/LineLength:
  Max: 525

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true
